/*
* Copyright (c).
*/
package de.tui.github.detail.domain;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class GithubDetailTest {

    @DisplayName("Test the equals hashcode and tostring methods as they tend to greatly reduce our test coverage even though they are autogenerated")
    @Test
    void testEntity() {
         GithubDetail gitdetail = new GithubDetail();
         assertNotNull(gitdetail.hashCode());
         assertEquals(true, gitdetail.equals(gitdetail));
         assertNotNull(gitdetail.toString());
         GithubDetail gitdetail2 = new GithubDetail();
         gitdetail2.setLastCommit("ID2");
         gitdetail2.setBranch("asdf");
         gitdetail2.setRepository("2sdfasd");
         gitdetail2.setLogin("asdf");
         assertEquals(false,gitdetail.equals(gitdetail2));
    }
}